import datetime

import requests

def get_historical_data(country="all"):
	r = requests.get(f'https://corona.lmao.ninja/v2/historical/{country}')
	return r.json()

def get_countries():
	COUNTRIES = ['Afghanistan',
             'Albania',
             'Algeria',
             'Andorra',
             'Angola',
             'Anguilla',
             'Antigua and Barbuda',
             'Argentina',
             'Armenia',
             'Aruba',
             'Australia',
             'Austria',
             'Azerbaijan',
             'Bahamas',
             'Bahrain',
             'Bangladesh',
             'Barbados',
             'Belarus',
             'Belgium',
             'Belize',
             'Benin',
             'Bermuda',
             'Bhutan',
             'Bolivia',
             'Bosnia',
             'Brazil',
             'British Virgin Islands',
             'Brunei',
             'Bulgaria',
             'Burkina Faso',
             'Central African Republic',
             'Cabo Verde',
             'Cambodia',
             'Cameroon',
             'Canada',
             'Cayman Islands',
             'Chad',
             'Channel Islands',
             'Chile',
             'China',
             'Colombia',
             'Congo',
             'Costa Rica',
             'Croatia',
             'Cuba',
             'Curaçao',
             'Cyprus',
             'Czechia',
             'DRC',
             'Denmark',
             'Diamond Princess',
             'Djibouti',
             'Dominica',
             'Dominican Republic',
             'Ecuador',
             'Egypt',
             'El Salvador',
             'Equatorial Guinea',
             'Eritrea',
             'Estonia',
             'Eswatini',
             'Ethiopia',
             'Faeroe Islands',
             'Fiji',
             'Finland',
             'France',
             'French Guiana',
             'French Polynesia',
             'Gabon',
             'Gambia',
             'Georgia',
             'Germany',
             'Ghana',
             'Gibraltar',
             'Greece',
             'Greenland',
             'Grenada',
             'Guadeloupe',
             'Guatemala',
             'Guinea',
             'Guinea-Bissau',
             'Guyana',
             'Haiti',
             'Honduras',
             'Hong Kong',
             'Hungary',
             'Iceland',
             'India',
             'Indonesia',
             'Iran',
             'Iraq',
             'Ireland',
             'Isle of Man',
             'Israel',
             'Italy',
             'Cote d\'Ivoire',
             'Jamaica',
             'Japan',
             'Jordan',
             'Kazakhstan',
             'Kenya',
             'Kuwait',
             'Kyrgyzstan',
             'Laos',
             'Latvia',
             'Lebanon',
             'Liberia',
             'Libya',
             'Liechtenstein',
             'Lithuania',
             'Luxembourg',
             'MS Zaandam',
             'Macao',
             'Madagascar',
             'Malaysia',
             'Maldives',
             'Mali',
             'Malta',
             'Martinique',
             'Mauritania',
             'Mauritius',
             'Mayotte',
             'Mexico',
             'Moldova',
             'Monaco',
             'Mongolia',
             'Montenegro',
             'Montserrat',
             'Morocco',
             'Mozambique',
             'Myanmar',
             'Namibia',
             'Nepal',
             'Netherlands',
             'New Caledonia',
             'New Zealand',
             'Nicaragua',
             'Niger',
             'Nigeria',
             'North Macedonia',
             'Norway',
             'Oman',
             'Pakistan',
             'Palestine',
             'Panama',
             'Papua New Guinea',
             'Paraguay',
             'Peru',
             'Philippines',
             'Poland',
             'Portugal',
             'Qatar',
             'Romania',
             'Russia',
             'Rwanda',
             'Réunion',
             'S. Korea',
             'Saint Kitts and Nevis',
             'Saint Lucia',
             'Saint Martin',
             'San Marino',
             'Saudi Arabia',
             'Senegal',
             'Serbia',
             'Seychelles',
             'Singapore',
             'Sint Maarten',
             'Slovakia',
             'Slovenia',
             'Somalia',
             'South Africa',
             'Spain',
             'Sri Lanka',
             'St. Barth',
             'Saint Vincent and the Grenadines',
             'Sudan',
             'Suriname',
             'Sweden',
             'Switzerland',
             'Syria',
             'Taiwan',
             'Tanzania',
             'Thailand',
             'Timor-Leste',
             'Togo',
             'Trinidad and Tobago',
             'Tunisia',
             'Turkey',
             'Turks and Caicos',
             'UAE',
             'UK',
             'USA',
             'Uganda',
             'Ukraine',
             'Uruguay',
             'Uzbekistan',
             'Vatican City',
             'Venezuela',
             'Vietnam',
             'West Bank and Gaza',
             'Zambia',
             'Zimbabwe']

	return COUNTRIES

def get_date_from_today(offset=0,fmt='%-m/%-d/%y'):
  today = datetime.datetime.now()
  targetDay = today + datetime.timedelta(offset)
  targetDayString = datetime.datetime.strftime(targetDay,fmt)
  return targetDayString

def get_death_daily_increase_rate(country="all"):
	data = get_historical_data(country=country)
	yday = get_date_from_today(offset=-1)
	week_before_yday = get_date_from_today(offset=-8)
	print(country)
	if country != "all":
		data = data['timeline']
	daily_growth = (data['deaths'][yday]/data['deaths'][week_before_yday])**(1/7)
	return daily_growth

def get_yesterdays_deathcount(country="all"):
	data = get_historical_data(country=country)
	yday = get_date_from_today(offset=-1)
	if country != "all":
		data = data['timeline']
	return data['deaths'][yday]

if __name__ == "__main__":
	rate = get_death_daily_increase_rate()
	print(rate) 